///*
// * This file was automatically generated by EvoSuite
// * Sat Jun 21 07:53:10 GMT 2025
// */
//
//package org.apache.bookkeeper.util;
//
//import org.junit.Ignore;
//import org.junit.Test;
//import static org.junit.Assert.*;
//import static org.evosuite.shaded.org.mockito.Mockito.*;
//import static org.evosuite.runtime.EvoAssertions.*;
//import io.netty.buffer.AdaptiveByteBufAllocator;
//import io.netty.buffer.ByteBuf;
//import io.netty.buffer.ByteBufAllocator;
//import io.netty.buffer.CompositeByteBuf;
//import io.netty.buffer.EmptyByteBuf;
//import io.netty.buffer.PooledByteBufAllocator;
//import io.netty.buffer.UnpooledByteBufAllocator;
//import io.netty.buffer.UnpooledDirectByteBuf;
//import io.netty.buffer.UnpooledUnsafeDirectByteBuf;
//import io.netty.channel.ChannelFuture;
//import io.netty.channel.ChannelHandler;
//import io.netty.channel.ChannelHandlerContext;
//import io.netty.channel.ChannelPromise;
//import io.netty.channel.DefaultChannelPromise;
//import io.netty.channel.embedded.EmbeddedChannel;
//import java.nio.ReadOnlyBufferException;
//import org.apache.bookkeeper.util.ByteBufList;
//import org.evosuite.runtime.EvoRunner;
//import org.evosuite.runtime.EvoRunnerParameters;
//import org.evosuite.runtime.ViolatedAssumptionAnswer;
//import org.junit.runner.RunWith;
//
///* true --> useVnet ma dà problemi con Netty */
//
//@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = false, resetStaticState = true, separateClassLoader = true)
//public class ByteBufList_ESTest extends ByteBufList_ESTest_scaffolding {
//
//  @Test(timeout = 4000)
//  public void test00()  throws Throwable  {
//      ByteBufList byteBufList0 = ByteBufList.get();
//      ChannelHandlerContext channelHandlerContext0 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
//      doReturn((ChannelPromise) null).when(channelHandlerContext0).newPromise();
//      ChannelHandler[] channelHandlerArray0 = new ChannelHandler[7];
//      EmbeddedChannel embeddedChannel0 = new EmbeddedChannel(channelHandlerArray0);
//      DefaultChannelPromise defaultChannelPromise0 = new DefaultChannelPromise(embeddedChannel0);
//      try {
//        byteBufList0.ENCODER.write(channelHandlerContext0, byteBufList0, defaultChannelPromise0);
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("org.apache.bookkeeper.util.ByteBufList$Encoder", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test01()  throws Throwable  {
//      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
//      CompositeByteBuf compositeByteBuf0 = new CompositeByteBuf(pooledByteBufAllocator0, false, 2326);
//      compositeByteBuf0.writeShort(2326);
//      ByteBufList byteBufList0 = ByteBufList.get((ByteBuf) compositeByteBuf0, (ByteBuf) compositeByteBuf0);
//      byte[] byteArray0 = new byte[6];
//      int int0 = byteBufList0.getBytes(byteArray0);
//      assertArrayEquals(new byte[] {(byte)9, (byte)22, (byte)9, (byte)22, (byte)0, (byte)0}, byteArray0);
//      assertEquals(4, int0);
//  }
//
//  @Test(timeout = 4000)
//  public void test02()  throws Throwable  {
//      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
//      CompositeByteBuf compositeByteBuf0 = new CompositeByteBuf(pooledByteBufAllocator0, false, 2326);
//      UnpooledUnsafeDirectByteBuf unpooledUnsafeDirectByteBuf0 = new UnpooledUnsafeDirectByteBuf(pooledByteBufAllocator0, 0, 0);
//      ByteBufList byteBufList0 = ByteBufList.get((ByteBuf) compositeByteBuf0, (ByteBuf) unpooledUnsafeDirectByteBuf0);
//      ByteBufList byteBufList1 = (ByteBufList)byteBufList0.touch((Object) unpooledUnsafeDirectByteBuf0);
//      assertEquals(2, byteBufList1.size());
//  }
//
//  @Test(timeout = 4000)
//  public void test03()  throws Throwable  {
//      AdaptiveByteBufAllocator adaptiveByteBufAllocator0 = new AdaptiveByteBufAllocator(false);
//      EmptyByteBuf emptyByteBuf0 = new EmptyByteBuf(adaptiveByteBufAllocator0);
//      ByteBufList byteBufList0 = ByteBufList.get((ByteBuf) emptyByteBuf0);
//      int int0 = byteBufList0.size();
//      assertEquals(1, int0);
//  }
//
//  @Test(timeout = 4000)
//  public void test04()  throws Throwable  {
//      ByteBufList byteBufList0 = ByteBufList.get();
//      ByteBufList byteBufList1 = byteBufList0.retain();
//      assertEquals(0, byteBufList1.size());
//  }
//
//  @Test(timeout = 4000)
//  public void test05()  throws Throwable  {
//      UnpooledByteBufAllocator unpooledByteBufAllocator0 = new UnpooledByteBufAllocator(false);
//      CompositeByteBuf compositeByteBuf0 = new CompositeByteBuf(unpooledByteBufAllocator0, false, 1003);
//      CompositeByteBuf compositeByteBuf1 = compositeByteBuf0.writeMedium(2376);
//      ByteBufList byteBufList0 = ByteBufList.get((ByteBuf) compositeByteBuf1);
//      int int0 = byteBufList0.readableBytes();
//      assertEquals(3, int0);
//  }
//
//  @Test(timeout = 4000)
//  public void test06()  throws Throwable  {
//      ByteBufList byteBufList0 = ByteBufList.get((ByteBuf) null, (ByteBuf) null);
//      ByteBuf byteBuf0 = byteBufList0.getBuffer(1);
//      assertNull(byteBuf0);
//  }
//
//  @Test(timeout = 4000)
//  public void test07()  throws Throwable  {
//      ByteBufList byteBufList0 = ByteBufList.get();
//      ByteBuf byteBuf0 = ByteBufList.coalesce(byteBufList0);
//      ByteBufList byteBufList1 = ByteBufList.get(byteBuf0);
//      ByteBuf byteBuf1 = byteBufList1.getBuffer(0);
//      assertSame(byteBuf1, byteBuf0);
//  }
//
//  @Test(timeout = 4000)
//  public void test08()  throws Throwable  {
//      ByteBufList byteBufList0 = ByteBufList.get();
//      ByteBufList byteBufList1 = ByteBufList.clone(byteBufList0);
//      assertNotSame(byteBufList1, byteBufList0);
//  }
//
//  @Test(timeout = 4000)
//  public void test09()  throws Throwable  {
//      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
//      CompositeByteBuf compositeByteBuf0 = new CompositeByteBuf(pooledByteBufAllocator0, false, 2326);
//      compositeByteBuf0.writeShort(2326);
//      ByteBufList byteBufList0 = ByteBufList.get((ByteBuf) compositeByteBuf0);
//      byte[] byteArray0 = byteBufList0.array();
//      assertEquals(64, byteArray0.length);
//  }
//
//  @Test(timeout = 4000)
//  public void test10()  throws Throwable  {
//      AdaptiveByteBufAllocator adaptiveByteBufAllocator0 = new AdaptiveByteBufAllocator(false, false);
//      CompositeByteBuf compositeByteBuf0 = adaptiveByteBufAllocator0.compositeDirectBuffer();
//      ByteBufList byteBufList0 = ByteBufList.get((ByteBuf) compositeByteBuf0);
//      byte[] byteArray0 = byteBufList0.array();
//      assertArrayEquals(new byte[] {}, byteArray0);
//  }
//
//  @Test(timeout = 4000)
//  public void test11()  throws Throwable  {
//      ByteBufList byteBufList0 = ByteBufList.get((ByteBuf) null);
//      Object object0 = new Object();
//      // Undeclared exception!
//      try {
//        byteBufList0.touch(object0);
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("org.apache.bookkeeper.util.ByteBufList", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test12()  throws Throwable  {
//      ByteBufList byteBufList0 = ByteBufList.get((ByteBuf) null);
//      // Undeclared exception!
//      try {
//        byteBufList0.toArray();
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("org.apache.bookkeeper.util.ByteBufList", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test13()  throws Throwable  {
//      ByteBufList byteBufList0 = ByteBufList.get();
//      byteBufList0.release();
//      // Undeclared exception!
//      try {
//        byteBufList0.retain();
//        fail("Expecting exception: IllegalStateException");
//
//      } catch(IllegalStateException e) {
//         //
//         // refCnt: 0, increment: 1
//         //
//         verifyException("io.netty.util.internal.ReferenceCountUpdater", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test14()  throws Throwable  {
//      ByteBufList byteBufList0 = ByteBufList.get((ByteBuf) null);
//      // Undeclared exception!
//      try {
//        byteBufList0.hasArray();
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("org.apache.bookkeeper.util.ByteBufList", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test15()  throws Throwable  {
//      AdaptiveByteBufAllocator adaptiveByteBufAllocator0 = new AdaptiveByteBufAllocator(false, false);
//      CompositeByteBuf compositeByteBuf0 = adaptiveByteBufAllocator0.compositeDirectBuffer();
//      ByteBufList byteBufList0 = ByteBufList.get((ByteBuf) compositeByteBuf0);
//      byteBufList0.deallocate();
//      byte[] byteArray0 = new byte[7];
//      ByteBufList byteBufList1 = ByteBufList.get((ByteBuf) compositeByteBuf0);
//      // Undeclared exception!
//      try {
//        byteBufList1.getBytes(byteArray0);
//        fail("Expecting exception: IllegalStateException");
//
//      } catch(IllegalStateException e) {
//         //
//         // refCnt: 0
//         //
//         verifyException("io.netty.buffer.AbstractByteBuf", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test16()  throws Throwable  {
//      AdaptiveByteBufAllocator adaptiveByteBufAllocator0 = new AdaptiveByteBufAllocator(true);
//      ByteBuf byteBuf0 = adaptiveByteBufAllocator0.buffer();
//      ByteBufList byteBufList0 = ByteBufList.get(byteBuf0);
//      // Undeclared exception!
//      try {
//        byteBufList0.getBytes((byte[]) null);
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("org.apache.bookkeeper.util.ByteBufList", e);
//      }
//  }
//
//
//  @Test(timeout = 4000)
//  public void test17()  throws Throwable  {
//      ByteBufList byteBufList0 = ByteBufList.get();
//      // Undeclared exception!
//      try {
//        byteBufList0.getBuffer(16);
//        fail("Expecting exception: IndexOutOfBoundsException");
//
//      } catch(IndexOutOfBoundsException e) {
//         //
//         // Index: 16, Size: 0
//         //
//         verifyException("java.util.ArrayList", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test18()  throws Throwable  {
//      ByteBufList byteBufList0 = ByteBufList.get();
//      ByteBuf byteBuf0 = ByteBufList.coalesce(byteBufList0);
//      ByteBufList byteBufList1 = ByteBufList.get(byteBuf0, byteBuf0);
//      // Undeclared exception!
//      try {
//        byteBufList1.deallocate();
//        fail("Expecting exception: IllegalStateException");
//
//      } catch(IllegalStateException e) {
//         //
//         // refCnt: 0, decrement: 1
//         //
//         verifyException("io.netty.util.internal.ReferenceCountUpdater", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test19()  throws Throwable  {
//      ByteBufList byteBufList0 = ByteBufList.get((ByteBuf) null, (ByteBuf) null);
//      // Undeclared exception!
//      try {
//        byteBufList0.deallocate();
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("org.apache.bookkeeper.util.ByteBufList", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test20()  throws Throwable  {
//      ByteBufList byteBufList0 = ByteBufList.get();
//      ByteBuf byteBuf0 = ByteBufList.coalesce(byteBufList0);
//      ByteBufList byteBufList1 = ByteBufList.get(byteBuf0);
//      ByteBufList byteBufList2 = ByteBufList.get(byteBuf0);
//      byteBufList2.deallocate();
//      // Undeclared exception!
//      try {
//        ByteBufList.coalesce(byteBufList1);
//        fail("Expecting exception: IllegalStateException");
//
//      } catch(IllegalStateException e) {
//         //
//         // refCnt: 0
//         //
//         verifyException("io.netty.buffer.AbstractByteBuf", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test21()  throws Throwable  {
//      // Undeclared exception!
//      try {
//        ByteBufList.coalesce((ByteBufList) null);
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("org.apache.bookkeeper.util.ByteBufList", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test22()  throws Throwable  {
//      ByteBufList byteBufList0 = ByteBufList.get();
//      ByteBuf byteBuf0 = ByteBufList.coalesce(byteBufList0);
//      ByteBufList byteBufList1 = ByteBufList.get(byteBuf0);
//      byteBufList1.deallocate();
//      ByteBufList byteBufList2 = ByteBufList.get(byteBuf0, byteBuf0);
//      // Undeclared exception!
//      try {
//        ByteBufList.clone(byteBufList2);
//        fail("Expecting exception: IllegalStateException");
//
//      } catch(IllegalStateException e) {
//         //
//         // refCnt: 0
//         //
//         verifyException("io.netty.buffer.AbstractByteBuf", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test23()  throws Throwable  {
//      // Undeclared exception!
//      try {
//        ByteBufList.clone((ByteBufList) null);
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("org.apache.bookkeeper.util.ByteBufList", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test24()  throws Throwable  {
//      AdaptiveByteBufAllocator adaptiveByteBufAllocator0 = new AdaptiveByteBufAllocator(false, false);
//      EmptyByteBuf emptyByteBuf0 = new EmptyByteBuf(adaptiveByteBufAllocator0);
//      ByteBuf byteBuf0 = emptyByteBuf0.asReadOnly();
//      ByteBufList byteBufList0 = ByteBufList.get(byteBuf0);
//      // Undeclared exception!
//      try {
//        byteBufList0.arrayOffset();
//        fail("Expecting exception: ReadOnlyBufferException");
//
//      } catch(ReadOnlyBufferException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("io.netty.buffer.ReadOnlyByteBuf", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test25()  throws Throwable  {
//      AdaptiveByteBufAllocator adaptiveByteBufAllocator0 = new AdaptiveByteBufAllocator(false, false);
//      ByteBuf byteBuf0 = adaptiveByteBufAllocator0.ioBuffer();
//      ByteBufList byteBufList0 = ByteBufList.get(byteBuf0, byteBuf0);
//      // Undeclared exception!
//      try {
//        byteBufList0.arrayOffset();
//        fail("Expecting exception: UnsupportedOperationException");
//
//      } catch(UnsupportedOperationException e) {
//         //
//         // direct buffer
//         //
//         verifyException("io.netty.buffer.UnpooledDirectByteBuf", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test26()  throws Throwable  {
//      ByteBufList byteBufList0 = ByteBufList.get((ByteBuf) null, (ByteBuf) null);
//      // Undeclared exception!
//      try {
//        byteBufList0.arrayOffset();
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("org.apache.bookkeeper.util.ByteBufList", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test27()  throws Throwable  {
//      ByteBufList byteBufList0 = ByteBufList.get();
//      // Undeclared exception!
//      try {
//        byteBufList0.arrayOffset();
//        fail("Expecting exception: IndexOutOfBoundsException");
//
//      } catch(IndexOutOfBoundsException e) {
//         //
//         // Index: 0, Size: 0
//         //
//         verifyException("java.util.ArrayList", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test28()  throws Throwable  {
//      AdaptiveByteBufAllocator adaptiveByteBufAllocator0 = new AdaptiveByteBufAllocator(false);
//      EmptyByteBuf emptyByteBuf0 = new EmptyByteBuf(adaptiveByteBufAllocator0);
//      ByteBuf byteBuf0 = emptyByteBuf0.asReadOnly();
//      ByteBufList byteBufList0 = ByteBufList.get(byteBuf0);
//      // Undeclared exception!
//      try {
//        byteBufList0.array();
//        fail("Expecting exception: ReadOnlyBufferException");
//
//      } catch(ReadOnlyBufferException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("io.netty.buffer.ReadOnlyByteBuf", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test29()  throws Throwable  {
//      ByteBufList byteBufList0 = ByteBufList.get();
//      PooledByteBufAllocator pooledByteBufAllocator0 = new PooledByteBufAllocator();
//      UnpooledDirectByteBuf unpooledDirectByteBuf0 = new UnpooledDirectByteBuf(pooledByteBufAllocator0, 5, 913);
//      byteBufList0.prepend(unpooledDirectByteBuf0);
//      // Undeclared exception!
//      try {
//        byteBufList0.array();
//        fail("Expecting exception: UnsupportedOperationException");
//
//      } catch(UnsupportedOperationException e) {
//         //
//         // direct buffer
//         //
//         verifyException("io.netty.buffer.UnpooledDirectByteBuf", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test30()  throws Throwable  {
//      ByteBufList byteBufList0 = ByteBufList.get((ByteBuf) null);
//      // Undeclared exception!
//      try {
//        byteBufList0.array();
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("org.apache.bookkeeper.util.ByteBufList", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test31()  throws Throwable  {
//      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
//      CompositeByteBuf compositeByteBuf0 = new CompositeByteBuf(pooledByteBufAllocator0, false, 2326);
//      byte[] byteArray0 = new byte[2];
//      compositeByteBuf0.writeBytes(byteArray0);
//      UnpooledUnsafeDirectByteBuf unpooledUnsafeDirectByteBuf0 = new UnpooledUnsafeDirectByteBuf(pooledByteBufAllocator0, 0, 0);
//      ByteBufList byteBufList0 = ByteBufList.get((ByteBuf) compositeByteBuf0, (ByteBuf) unpooledUnsafeDirectByteBuf0);
//      int int0 = byteBufList0.getBytes(byteArray0);
//      assertEquals(2, int0);
//  }
//
//  @Test(timeout = 4000)
//  public void test32()  throws Throwable  {
//      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
//      CompositeByteBuf compositeByteBuf0 = new CompositeByteBuf(pooledByteBufAllocator0, false, 2326);
//      byte[] byteArray0 = new byte[2];
//      UnpooledUnsafeDirectByteBuf unpooledUnsafeDirectByteBuf0 = new UnpooledUnsafeDirectByteBuf(pooledByteBufAllocator0, 0, 0);
//      ByteBufList byteBufList0 = ByteBufList.get((ByteBuf) compositeByteBuf0, (ByteBuf) unpooledUnsafeDirectByteBuf0);
//      int int0 = byteBufList0.getBytes(byteArray0);
//      assertEquals(0, int0);
//  }
//
//  @Test(timeout = 4000)
//  public void test33()  throws Throwable  {
//      AdaptiveByteBufAllocator adaptiveByteBufAllocator0 = new AdaptiveByteBufAllocator(false, false);
//      EmptyByteBuf emptyByteBuf0 = new EmptyByteBuf(adaptiveByteBufAllocator0);
//      ByteBufList byteBufList0 = ByteBufList.get((ByteBuf) emptyByteBuf0);
//      int int0 = byteBufList0.readableBytes();
//      assertEquals(0, int0);
//  }
//
//  @Test(timeout = 4000)
//  public void test34()  throws Throwable  {
//      ByteBufList byteBufList0 = ByteBufList.get((ByteBuf) null, (ByteBuf) null);
//      // Undeclared exception!
//      try {
//        byteBufList0.readableBytes();
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("org.apache.bookkeeper.util.ByteBufList", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test35()  throws Throwable  {
//      ByteBufList byteBufList0 = ByteBufList.get();
//      ByteBuf byteBuf0 = ByteBufList.coalesce(byteBufList0);
//      byteBufList0.add(byteBuf0);
//      assertEquals(1, byteBufList0.size());
//  }
//
//  @Test(timeout = 4000)
//  public void test36()  throws Throwable  {
//      ByteBufList byteBufList0 = ByteBufList.get();
//      EmbeddedChannel embeddedChannel0 = new EmbeddedChannel();
//      DefaultChannelPromise defaultChannelPromise0 = new DefaultChannelPromise(embeddedChannel0);
//      ChannelHandlerContext channelHandlerContext0 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
//      doReturn(defaultChannelPromise0).when(channelHandlerContext0).newPromise();
//      byteBufList0.ENCODER.write(channelHandlerContext0, byteBufList0, defaultChannelPromise0);
//      assertFalse(defaultChannelPromise0.isVoid());
//  }
//
//  @Test(timeout = 4000)
//  public void test37()  throws Throwable  {
//      ByteBufList byteBufList0 = ByteBufList.get();
//      ChannelHandlerContext channelHandlerContext0 = mock(ChannelHandlerContext.class, new ViolatedAssumptionAnswer());
//      doReturn((ChannelFuture) null).when(channelHandlerContext0).write(any() , any(ChannelPromise.class));
//      byteBufList0.ENCODER.write(channelHandlerContext0, (Object) null, (ChannelPromise) null);
//      assertEquals(0, byteBufList0.size());
//  }
//
//  @Test(timeout = 4000)
//  public void test38()  throws Throwable  {
//      ByteBufList byteBufList0 = ByteBufList.get();
//      ByteBuf byteBuf0 = ByteBufList.coalesce(byteBufList0);
//      ByteBufList byteBufList1 = ByteBufList.get(byteBuf0);
//      byteBufList1.deallocate();
//      ByteBufList byteBufList2 = ByteBufList.get(byteBuf0);
//      // Undeclared exception!
//      try {
//        byteBufList2.array();
//        fail("Expecting exception: IllegalStateException");
//
//      } catch(IllegalStateException e) {
//         //
//         // refCnt: 0
//         //
//         verifyException("io.netty.buffer.AbstractByteBuf", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test39()  throws Throwable  {
//      AdaptiveByteBufAllocator adaptiveByteBufAllocator0 = new AdaptiveByteBufAllocator(false, false);
//      EmptyByteBuf emptyByteBuf0 = new EmptyByteBuf(adaptiveByteBufAllocator0);
//      ByteBuf byteBuf0 = emptyByteBuf0.asReadOnly();
//      ByteBufList byteBufList0 = ByteBufList.get(byteBuf0);
//      boolean boolean0 = byteBufList0.hasArray();
//      assertFalse(boolean0);
//  }
//
//  @Test(timeout = 4000)
//  public void test40()  throws Throwable  {
//      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
//      CompositeByteBuf compositeByteBuf0 = new CompositeByteBuf(pooledByteBufAllocator0, false, 2326);
//      ByteBufList byteBufList0 = ByteBufList.get((ByteBuf) compositeByteBuf0);
//      boolean boolean0 = byteBufList0.hasArray();
//      assertTrue(boolean0);
//  }
//
//  @Test(timeout = 4000)
//  public void test41()  throws Throwable  {
//      ByteBufList byteBufList0 = ByteBufList.get();
//      boolean boolean0 = byteBufList0.hasArray();
//      assertFalse(boolean0);
//  }
//
//  @Ignore("Skipped due to failing assertion expected:<0> but was:<1>")
//  @Test(timeout = 4000)
//  public void test42()  throws Throwable  {
//      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
//      CompositeByteBuf compositeByteBuf0 = new CompositeByteBuf(pooledByteBufAllocator0, false, 2326);
//      assertEquals(0, pooledByteBufAllocator0.numThreadLocalCaches());
//
//      byte[] byteArray0 = new byte[2];
//      compositeByteBuf0.writeBytes(byteArray0);
//      UnpooledUnsafeDirectByteBuf unpooledUnsafeDirectByteBuf0 = new UnpooledUnsafeDirectByteBuf(pooledByteBufAllocator0, 0, 0);
//      ByteBufList byteBufList0 = ByteBufList.get((ByteBuf) compositeByteBuf0, (ByteBuf) unpooledUnsafeDirectByteBuf0);
//      byte[] byteArray1 = byteBufList0.toArray();
//      assertArrayEquals(new byte[] {(byte)0, (byte)0}, byteArray1);
//  }
//
//  @Test(timeout = 4000)
//  public void test43()  throws Throwable  {
//      ByteBufList byteBufList0 = ByteBufList.get();
//      byte[] byteArray0 = byteBufList0.toArray();
//      assertEquals(0, byteArray0.length);
//  }
//
//  @Test(timeout = 4000)
//  public void test44()  throws Throwable  {
//      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
//      CompositeByteBuf compositeByteBuf0 = new CompositeByteBuf(pooledByteBufAllocator0, false, 2326);
//      ByteBufList byteBufList0 = ByteBufList.get((ByteBuf) compositeByteBuf0);
//      ByteBufList byteBufList1 = ByteBufList.clone(byteBufList0);
//      assertEquals(1, byteBufList1.size());
//      assertNotSame(byteBufList1, byteBufList0);
//  }
//
//  @Test(timeout = 4000)
//  public void test45()  throws Throwable  {
//      ByteBufList.Encoder byteBufList_Encoder0 = new ByteBufList.Encoder();
//  }
//
//  @Test(timeout = 4000)
//  public void test46()  throws Throwable  {
//      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
//      CompositeByteBuf compositeByteBuf0 = new CompositeByteBuf(pooledByteBufAllocator0, false, 2326);
//      UnpooledUnsafeDirectByteBuf unpooledUnsafeDirectByteBuf0 = new UnpooledUnsafeDirectByteBuf(pooledByteBufAllocator0, 0, 0);
//      ByteBufList byteBufList0 = ByteBufList.get((ByteBuf) compositeByteBuf0, (ByteBuf) unpooledUnsafeDirectByteBuf0);
//      // Undeclared exception!
//      try {
//        byteBufList0.getBuffer((-1732));
//        fail("Expecting exception: ArrayIndexOutOfBoundsException");
//
//      } catch(ArrayIndexOutOfBoundsException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test47()  throws Throwable  {
//      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
//      CompositeByteBuf compositeByteBuf0 = new CompositeByteBuf(pooledByteBufAllocator0, false, 2326);
//      ByteBufList byteBufList0 = ByteBufList.get((ByteBuf) compositeByteBuf0);
//      ByteBufList byteBufList1 = byteBufList0.retain();
//      assertSame(byteBufList0, byteBufList1);
//  }
//
//  @Test(timeout = 4000)
//  public void test48()  throws Throwable  {
//      ByteBufList byteBufList0 = ByteBufList.get();
//      int int0 = byteBufList0.size();
//      assertEquals(0, int0);
//  }
//
//  @Test(timeout = 4000)
//  public void test49()  throws Throwable  {
//      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
//      CompositeByteBuf compositeByteBuf0 = new CompositeByteBuf(pooledByteBufAllocator0, false, 2326);
//      ByteBufList byteBufList0 = ByteBufList.get((ByteBuf) compositeByteBuf0);
//      int int0 = byteBufList0.arrayOffset();
//      assertEquals(0, int0);
//  }
//
//  @Ignore("Netty")
//  @Test(timeout = 4000)
//  public void test50()  throws Throwable  {
//      ByteBufList byteBufList0 = ByteBufList.get();
//      // Undeclared exception!
//      try {
//        byteBufList0.array();
//        fail("Expecting exception: IndexOutOfBoundsException");
//
//      } catch(IndexOutOfBoundsException e) {
//         //
//         // Index: 0, Size: 0
//         //
//         verifyException("java.util.ArrayList", e);
//      }
//  }
//}
