///*
// * This file was automatically generated by EvoSuite
// * Wed Jun 18 08:02:54 GMT 2025
// */
//
//package org.apache.bookkeeper.util;
//
//import org.junit.Test;
//import static org.junit.Assert.*;
//import org.apache.bookkeeper.util.foo;
//import org.evosuite.runtime.EvoRunner;
//import org.evosuite.runtime.EvoRunnerParameters;
//import org.junit.runner.RunWith;
//
//@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
//public class foo_ESTest extends foo_ESTest_scaffolding {
//
//  @Test(timeout = 4000)
//  public void test0()  throws Throwable  {
//      foo foo0 = new foo();
//      int int0 = foo0.sum((-1), 0);
//      assertEquals(0, int0);
//  }
//
//  @Test(timeout = 4000)
//  public void test1()  throws Throwable  {
//      foo foo0 = new foo();
//      int int0 = foo0.sum(0, 0);
//      assertEquals(0, int0);
//  }
//
//  @Test(timeout = 4000)
//  public void test2()  throws Throwable  {
//      foo foo0 = new foo();
//      int int0 = foo0.sum(0, 499);
//      assertEquals(499, int0);
//  }
//
//  @Test(timeout = 4000)
//  public void test3()  throws Throwable  {
//      foo foo0 = new foo();
//      int int0 = foo0.sum((-1), (-1));
//      assertEquals((-1), int0);
//  }
//
//  @Test(timeout = 4000)
//  public void test4()  throws Throwable  {
//      foo foo0 = new foo();
//      int int0 = foo0.sum(968, 0);
//      assertEquals(968, int0);
//  }
//}
