/*
 * This file was automatically generated by EvoSuite
 * Sat Jun 21 09:36:09 GMT 2025
 */

package org.apache.bookkeeper.bookie;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import io.netty.buffer.AdaptiveByteBufAllocator;
import io.netty.buffer.ByteBuf;
import io.netty.buffer.ByteBufAllocator;
import io.netty.buffer.EmptyByteBuf;
import io.netty.buffer.PooledByteBufAllocator;
import io.netty.buffer.UnpooledUnsafeDirectByteBuf;
import java.io.FileDescriptor;
import java.io.IOException;
import java.nio.channels.ClosedChannelException;
import java.nio.channels.FileChannel;
import org.apache.bookkeeper.bookie.BufferedChannel;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.System;
import org.evosuite.runtime.mock.java.io.MockFileInputStream;
import org.evosuite.runtime.mock.java.io.MockFileOutputStream;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class BufferedChannel_ESTest extends BufferedChannel_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("y8W~");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      ByteBuf byteBuf0 = pooledByteBufAllocator0.heapBuffer(69, 69);
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 69);
      // Undeclared exception!
      try { 
        bufferedChannel0.read(byteBuf0, 4611686018427387903L);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // srcIndex: -1, length: 1 (expected: range(0, 69))
         //
         verifyException("io.netty.buffer.AbstractByteBuf", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream(":>n03.sy5).7(5L'{\"", false);
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 0);
      bufferedChannel0.size();
      BufferedChannel bufferedChannel1 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 0);
      bufferedChannel1.flushAndForceWrite(false);
      EmptyByteBuf emptyByteBuf0 = new EmptyByteBuf(pooledByteBufAllocator0);
      int int0 = bufferedChannel1.read((ByteBuf) emptyByteBuf0, (long) 0, (-1));
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream(":>n03.sy5).7(5L'{\"", true);
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 0);
      mockFileOutputStream0.release();
      long long0 = bufferedChannel0.size();
      bufferedChannel0.size();
      FileChannel fileChannel1 = fileChannel0.position(401L);
      BufferedChannel bufferedChannel1 = new BufferedChannel(pooledByteBufAllocator0, fileChannel1, 0);
      bufferedChannel1.size();
      bufferedChannel0.forceWrite(true);
      mockFileOutputStream0.release();
      PooledByteBufAllocator pooledByteBufAllocator1 = PooledByteBufAllocator.DEFAULT;
      BufferedChannel bufferedChannel2 = new BufferedChannel(pooledByteBufAllocator1, fileChannel1, 0, 0);
      bufferedChannel2.flush();
      boolean boolean0 = true;
      bufferedChannel0.flushAndForceWrite(boolean0);
      long long1 = (-1L);
      System.setCurrentTimeMillis(long1);
      assertFalse(long1 == long0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("q1{*V7kX,M|].X|?fl>", false);
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 0, 0, (-2616L));
      mockFileOutputStream0.release();
      bufferedChannel0.flush();
      bufferedChannel0.flushAndForceWrite(true);
      assertEquals(0L, bufferedChannel0.getFileChannelPosition());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream(":>n03.sy5).7(5L'{\"", false);
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 0);
      bufferedChannel0.size();
      BufferedChannel bufferedChannel1 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 0, 291L);
      long long0 = bufferedChannel0.forceWrite(false);
      assertEquals(0L, long0);
      
      long long1 = bufferedChannel0.getFileChannelPosition();
      assertEquals(0L, long1);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("y8W~");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 34);
      // Undeclared exception!
      try { 
        bufferedChannel0.write((ByteBuf) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.bookie.BufferedChannel", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("G~9bsak{>&");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 1);
      bufferedChannel0.getNumOfBytesInWriteBuffer();
      // Undeclared exception!
      try { 
        bufferedChannel0.read((ByteBuf) null, (-2904L), 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.bookie.BufferedChannel", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("y8W~");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      ByteBuf byteBuf0 = pooledByteBufAllocator0.heapBuffer(58, 58);
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 58);
      // Undeclared exception!
      try { 
        bufferedChannel0.read(byteBuf0, 634L, 58);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // minWritableBytes : -634 (expected: >= 0)
         //
         verifyException("io.netty.util.internal.ObjectUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("y8W~");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 34);
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("y8W~");
      FileSystemHandling.shouldThrowIOException(evoSuiteFile0);
      try { 
        bufferedChannel0.flush();
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Simulated IOException
         //
         verifyException("org.evosuite.runtime.vfs.VirtualFileSystem", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("y8W~");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      fileChannel0.close();
      BufferedChannel bufferedChannel0 = null;
      try {
        bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 34, 1000000000L);
        fail("Expecting exception: ClosedChannelException");
      
      } catch(Throwable e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.EvoFileChannel", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      AdaptiveByteBufAllocator adaptiveByteBufAllocator0 = new AdaptiveByteBufAllocator();
      BufferedChannel bufferedChannel0 = null;
      try {
        bufferedChannel0 = new BufferedChannel(adaptiveByteBufAllocator0, (FileChannel) null, 33, (-1L));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.bookie.BufferedChannel", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("y8W~");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      BufferedChannel bufferedChannel0 = null;
      try {
        bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, (-614), (-614));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // initialCapacity : -614 (expected: >= 0)
         //
         verifyException("io.netty.util.internal.ObjectUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      FileSystemHandling.shouldAllThrowIOExceptions();
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream(":>n03.sy5).7(5L'{\"");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      BufferedChannel bufferedChannel0 = null;
      try {
        bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 0, 1505L);
        fail("Expecting exception: IOException");
      
      } catch(Throwable e) {
         //
         // Simulated IOException
         //
         verifyException("org.evosuite.runtime.vfs.VirtualFileSystem", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("O8U|~");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      mockFileOutputStream0.close();
      BufferedChannel bufferedChannel0 = null;
      try {
        bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 1096, 1096, 1096);
        fail("Expecting exception: ClosedChannelException");
      
      } catch(Throwable e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.EvoFileChannel", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      BufferedChannel bufferedChannel0 = null;
      try {
        bufferedChannel0 = new BufferedChannel((ByteBufAllocator) null, (FileChannel) null, 1, 1, 9L);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.bookie.BufferedChannel", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      FileDescriptor fileDescriptor0 = new FileDescriptor();
      MockFileInputStream mockFileInputStream0 = new MockFileInputStream(fileDescriptor0);
      FileChannel fileChannel0 = mockFileInputStream0.getChannel();
      BufferedChannel bufferedChannel0 = null;
      try {
        bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, (-646), 2430, (-646));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // initialCapacity : -646 (expected: >= 0)
         //
         verifyException("io.netty.util.internal.ObjectUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream(",8UWRw");
      FileSystemHandling.shouldAllThrowIOExceptions();
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      BufferedChannel bufferedChannel0 = null;
      try {
        bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 1096, 1096, 1L);
        fail("Expecting exception: IOException");
      
      } catch(Throwable e) {
         //
         // Simulated IOException
         //
         verifyException("org.evosuite.runtime.vfs.VirtualFileSystem", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream(":>n03.syn)p7(5L|*'{\"");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      mockFileOutputStream0.close();
      BufferedChannel bufferedChannel0 = null;
      try {
        bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 20);
        fail("Expecting exception: ClosedChannelException");
      
      } catch(Throwable e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.EvoFileChannel", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      BufferedChannel bufferedChannel0 = null;
      try {
        bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, (FileChannel) null, 58);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.bookkeeper.bookie.BufferedChannel", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("*qGZZXAA");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      FileSystemHandling.shouldAllThrowIOExceptions();
      BufferedChannel bufferedChannel0 = null;
      try {
        bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 20);
        fail("Expecting exception: IOException");
      
      } catch(Throwable e) {
         //
         // Simulated IOException
         //
         verifyException("org.evosuite.runtime.vfs.VirtualFileSystem", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream(":>n03.sy5).7(5L'{\"", false);
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 0);
      bufferedChannel0.size();
      bufferedChannel0.forceWrite(false);
      mockFileOutputStream0.release();
      FileSystemHandling.shouldAllThrowIOExceptions();
      EmptyByteBuf emptyByteBuf0 = new EmptyByteBuf(pooledByteBufAllocator0);
      EmptyByteBuf emptyByteBuf1 = new EmptyByteBuf(pooledByteBufAllocator0);
      bufferedChannel0.read((ByteBuf) emptyByteBuf1, 4096L, 0);
      bufferedChannel0.getUnpersistedBytes();
      System.setCurrentTimeMillis(120L);
      try { 
        bufferedChannel0.forceWrite(false);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Simulated IOException
         //
         verifyException("org.evosuite.runtime.vfs.VirtualFileSystem", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("y8W~");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      ByteBuf byteBuf0 = pooledByteBufAllocator0.heapBuffer(58, 58);
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 58);
      bufferedChannel0.readBufferStartPosition = (long) 58;
      // Undeclared exception!
      try { 
        bufferedChannel0.read(byteBuf0, (-141L), 58);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Negative position: -141
         //
         verifyException("org.evosuite.runtime.mock.java.io.EvoFileChannel", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("Read past EOF");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      ByteBuf byteBuf0 = pooledByteBufAllocator0.heapBuffer(55, 58);
      FileChannel fileChannel1 = fileChannel0.position((long) 55);
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel1, 58);
      try { 
        bufferedChannel0.read(byteBuf0, (long) 55);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Read past EOF
         //
         verifyException("org.apache.bookkeeper.bookie.BufferedChannel", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("y8W~");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      ByteBuf byteBuf0 = pooledByteBufAllocator0.heapBuffer(58, 58);
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 58);
      // Undeclared exception!
      try { 
        bufferedChannel0.read(byteBuf0, (-813L));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Negative position: -813
         //
         verifyException("org.evosuite.runtime.mock.java.io.EvoFileChannel", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream(":>n03.sy5).7(5L'{\"", true);
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 0);
      mockFileOutputStream0.release();
      bufferedChannel0.size();
      bufferedChannel0.size();
      BufferedChannel bufferedChannel1 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 0, 0, 401L);
      long long0 = bufferedChannel1.forceWrite(false);
      assertEquals(0L, long0);
      
      FileChannel fileChannel1 = mockFileOutputStream0.getChannel();
      BufferedChannel bufferedChannel2 = new BufferedChannel(pooledByteBufAllocator0, fileChannel1, 0);
      bufferedChannel1.clear();
      bufferedChannel0.position();
      bufferedChannel1.flushAndForceWrite(false);
      EmptyByteBuf emptyByteBuf0 = new EmptyByteBuf(pooledByteBufAllocator0);
      ByteBuf byteBuf0 = emptyByteBuf0.writeZero(0);
      bufferedChannel1.write(byteBuf0);
      bufferedChannel2.flushAndForceWrite(true);
      bufferedChannel1.forceWrite(true);
      assertEquals(0L, bufferedChannel1.position());
      
      bufferedChannel0.write(byteBuf0);
      assertEquals(0L, bufferedChannel0.position());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream(",8UWRI");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 1, 1, 1L);
      UnpooledUnsafeDirectByteBuf unpooledUnsafeDirectByteBuf0 = new UnpooledUnsafeDirectByteBuf(pooledByteBufAllocator0, 1101, 1101);
      ByteBuf byteBuf0 = unpooledUnsafeDirectByteBuf0.writeInt(1101);
      bufferedChannel0.write(byteBuf0);
      assertEquals(4L, bufferedChannel0.position());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream(":>n03.sy5).7(5L'{\"");
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 0);
      BufferedChannel bufferedChannel1 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 255);
      bufferedChannel0.flushAndForceWriteIfRegularFlush(true);
      bufferedChannel0.close();
      bufferedChannel0.close();
      assertFalse(fileChannel0.isOpen());
      assertEquals(0L, bufferedChannel0.getFileChannelPosition());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
      //  // Unstable assertion: assertEquals(0, pooledByteBufAllocator0.numThreadLocalCaches());
      
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream(":>n03.sy5).7(5L'{\"", false);
      byte[] byteArray0 = new byte[3];
      byteArray0[0] = (byte)1;
      byteArray0[1] = (byte)64;
      byteArray0[2] = (byte)33;
      mockFileOutputStream0.write(byteArray0);
      FileChannel fileChannel0 = mockFileOutputStream0.getChannel();
      BufferedChannel bufferedChannel0 = new BufferedChannel(pooledByteBufAllocator0, fileChannel0, 0);
      bufferedChannel0.size();
      bufferedChannel0.forceWrite(false);
      EmptyByteBuf emptyByteBuf0 = new EmptyByteBuf(pooledByteBufAllocator0);
      emptyByteBuf0.writeZero(0);
      bufferedChannel0.write(emptyByteBuf0);
      bufferedChannel0.position();
      long long0 = bufferedChannel0.getFileChannelPosition();
      //  // Unstable assertion: assertEquals(3L, long0);
  }
}
