///*
// * This file was automatically generated by EvoSuite
// * Sat Jun 21 09:25:58 GMT 2025
// */
//
//package org.apache.bookkeeper.bookie;
//
//import org.junit.Test;
//import static org.junit.Assert.*;
//import static org.evosuite.shaded.org.mockito.Mockito.*;
//import static org.evosuite.runtime.EvoAssertions.*;
//import io.netty.buffer.AdaptiveByteBufAllocator;
//import io.netty.buffer.ByteBuf;
//import io.netty.buffer.ByteBufAllocator;
//import io.netty.buffer.CompositeByteBuf;
//import io.netty.buffer.EmptyByteBuf;
//import io.netty.buffer.PooledByteBufAllocator;
//import io.netty.buffer.UnpooledByteBufAllocator;
//import io.prometheus.client.CollectorRegistry;
//import java.io.File;
//import java.util.List;
//import org.apache.bookkeeper.bookie.BookieImpl;
//import org.apache.bookkeeper.bookie.Journal;
//import org.apache.bookkeeper.bookie.JournalAliveListener;
//import org.apache.bookkeeper.bookie.JournalChannel;
//import org.apache.bookkeeper.bookie.LedgerDirsManager;
//import org.apache.bookkeeper.conf.ServerConfiguration;
//import org.apache.bookkeeper.stats.CachingStatsLogger;
//import org.apache.bookkeeper.stats.Counter;
//import org.apache.bookkeeper.stats.NullStatsLogger;
//import org.apache.bookkeeper.stats.OpStatsLogger;
//import org.apache.bookkeeper.stats.StatsLogger;
//import org.apache.bookkeeper.stats.prometheus.PrometheusMetricsProvider;
//import org.apache.bookkeeper.util.DiskChecker;
//import org.evosuite.runtime.EvoRunner;
//import org.evosuite.runtime.EvoRunnerParameters;
//import org.evosuite.runtime.ViolatedAssumptionAnswer;
//import org.evosuite.runtime.mock.java.io.MockFile;
//import org.evosuite.runtime.testdata.EvoSuiteFile;
//import org.evosuite.runtime.testdata.FileSystemHandling;
//import org.junit.runner.RunWith;
//
//@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = false, resetStaticState = true, separateClassLoader = true)
//public class Journal_ESTest extends Journal_ESTest_scaffolding {
//
//  @Test(timeout = 4000)
//  public void test00()  throws Throwable  {
//      JournalChannel journalChannel0 = new JournalChannel((File) null, (-1L));
//      AdaptiveByteBufAllocator adaptiveByteBufAllocator0 = new AdaptiveByteBufAllocator();
//      CompositeByteBuf compositeByteBuf0 = adaptiveByteBufAllocator0.compositeHeapBuffer(394);
//      // Undeclared exception!
//      try {
//        Journal.writePaddingBytes(journalChannel0, compositeByteBuf0, (-500));
//        fail("Expecting exception: IndexOutOfBoundsException");
//
//      } catch(IndexOutOfBoundsException e) {
//         //
//         // readerIndex: 0, writerIndex: -1012 (expected: 0 <= readerIndex <= writerIndex <= capacity(64))
//         //
//         verifyException("io.netty.buffer.AbstractByteBuf", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test01()  throws Throwable  {
//      MockFile mockFile0 = new MockFile("");
//      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
//      ServerConfiguration serverConfiguration1 = serverConfiguration0.setJournalAdaptiveGroupWrites(false);
//      File[] fileArray0 = new File[6];
//      fileArray0[0] = (File) mockFile0;
//      fileArray0[1] = (File) mockFile0;
//      fileArray0[2] = (File) mockFile0;
//      fileArray0[3] = (File) mockFile0;
//      fileArray0[4] = (File) mockFile0;
//      fileArray0[5] = (File) mockFile0;
//      LedgerDirsManager ledgerDirsManager0 = new LedgerDirsManager(serverConfiguration1, fileArray0, (DiskChecker) null);
//      Journal journal0 = null;
//      try {
//        journal0 = new Journal(4, fileArray0[1], serverConfiguration0, ledgerDirsManager0);
//        fail("Expecting exception: RuntimeException");
//
//      } catch(RuntimeException e) {
//         //
//         // org.evosuite.runtime.mock.java.lang.MockThrowable: java.lang.ClassNotFoundException: java.lang.String@0000000031
//         //
//         verifyException("org.apache.bookkeeper.bookie.Journal", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test02()  throws Throwable  {
//      BookieImpl.NopWriteCallback bookieImpl_NopWriteCallback0 = new BookieImpl.NopWriteCallback();
//      NullStatsLogger nullStatsLogger0 = new NullStatsLogger();
//      OpStatsLogger opStatsLogger0 = nullStatsLogger0.getOpStatsLogger("status");
//      CachingStatsLogger cachingStatsLogger0 = new CachingStatsLogger(nullStatsLogger0);
//      Counter counter0 = cachingStatsLogger0.getThreadScopedCounter("sers");
//      Journal.QueueEntry journal_QueueEntry0 = Journal.QueueEntry.create((ByteBuf) null, true, (-2168L), 4599L, bookieImpl_NopWriteCallback0, "sers", 1000000000000000L, opStatsLogger0, counter0);
//      journal_QueueEntry0.run();
//  }
//
//  @Test(timeout = 4000)
//  public void test03()  throws Throwable  {
//      MockFile mockFile0 = new MockFile("");
//      JournalChannel journalChannel0 = new JournalChannel(mockFile0, (-8192L));
//      AdaptiveByteBufAllocator adaptiveByteBufAllocator0 = new AdaptiveByteBufAllocator(true);
//      ByteBuf byteBuf0 = adaptiveByteBufAllocator0.ioBuffer();
//      Journal.writePaddingBytes(journalChannel0, byteBuf0, 6);
//  }
//
//  @Test(timeout = 4000)
//  public void test04()  throws Throwable  {
//      MockFile mockFile0 = new MockFile("");
//      JournalChannel journalChannel0 = new JournalChannel(mockFile0, (-8192L));
//      AdaptiveByteBufAllocator adaptiveByteBufAllocator0 = new AdaptiveByteBufAllocator(false);
//      ByteBuf byteBuf0 = adaptiveByteBufAllocator0.ioBuffer(6, 6);
//      // Undeclared exception!
//      try {
//        Journal.writePaddingBytes(journalChannel0, byteBuf0, 13);
//        fail("Expecting exception: IndexOutOfBoundsException");
//
//      } catch(IndexOutOfBoundsException e) {
//         //
//         // writerIndex(4) + minWritableBytes(4) exceeds maxCapacity(6): AdaptivePoolingAllocator$AdaptiveByteBuf(ridx: 0, widx: 4, cap: 6/6)
//         //
//         verifyException("io.netty.buffer.AbstractByteBuf", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test05()  throws Throwable  {
//      JournalChannel journalChannel0 = new JournalChannel((File) null, 646L);
//      UnpooledByteBufAllocator unpooledByteBufAllocator0 = UnpooledByteBufAllocator.DEFAULT;
//      EmptyByteBuf emptyByteBuf0 = new EmptyByteBuf(unpooledByteBufAllocator0);
//      // Undeclared exception!
//      try {
//        Journal.writePaddingBytes(journalChannel0, emptyByteBuf0, 0);
//        fail("Expecting exception: ArithmeticException");
//
//      } catch(ArithmeticException e) {
//         //
//         // / by zero
//         //
//         verifyException("org.apache.bookkeeper.bookie.Journal", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test06()  throws Throwable  {
//      MockFile mockFile0 = new MockFile(" (this is okay if it is the first time starting this bookie", "");
//      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
//      ServerConfiguration serverConfiguration1 = serverConfiguration0.setMaxBackupJournals(1);
//      File[] fileArray0 = new File[0];
//      DiskChecker diskChecker0 = new DiskChecker(0.5F, 0);
//      NullStatsLogger nullStatsLogger0 = NullStatsLogger.INSTANCE;
//      CachingStatsLogger cachingStatsLogger0 = new CachingStatsLogger(nullStatsLogger0);
//      LedgerDirsManager ledgerDirsManager0 = new LedgerDirsManager(serverConfiguration1, fileArray0, diskChecker0, cachingStatsLogger0);
//      AdaptiveByteBufAllocator adaptiveByteBufAllocator0 = new AdaptiveByteBufAllocator();
//      // Undeclared exception!
//      try {
//        Journal.newJournal(0, mockFile0, serverConfiguration0, ledgerDirsManager0, cachingStatsLogger0, adaptiveByteBufAllocator0, (JournalAliveListener) null);
//        fail("Expecting exception: RuntimeException");
//
//      } catch(RuntimeException e) {
//         //
//         // 'journalMaxBackups' doesn't map to an Integer object
//         //
//         verifyException("org.apache.commons.configuration.AbstractConfiguration", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test07()  throws Throwable  {
//      MockFile mockFile0 = new MockFile(" (this is okay if it is the first time starting this bookie", "");
//      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
//      File[] fileArray0 = new File[0];
//      DiskChecker diskChecker0 = new DiskChecker(0.5F, 0);
//      NullStatsLogger nullStatsLogger0 = NullStatsLogger.INSTANCE;
//      CachingStatsLogger cachingStatsLogger0 = new CachingStatsLogger(nullStatsLogger0);
//      LedgerDirsManager ledgerDirsManager0 = new LedgerDirsManager(serverConfiguration0, fileArray0, diskChecker0, cachingStatsLogger0);
//      AdaptiveByteBufAllocator adaptiveByteBufAllocator0 = new AdaptiveByteBufAllocator();
//      // Undeclared exception!
//      try {
//        Journal.newJournal(0, mockFile0, serverConfiguration0, ledgerDirsManager0, cachingStatsLogger0, adaptiveByteBufAllocator0, (JournalAliveListener) null);
//        fail("Expecting exception: RuntimeException");
//
//      } catch(RuntimeException e) {
//         //
//         // org.evosuite.runtime.mock.java.lang.MockThrowable: java.lang.ClassNotFoundException: java.lang.String@0000000061
//         //
//         verifyException("org.apache.bookkeeper.bookie.Journal", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test08()  throws Throwable  {
//      // Undeclared exception!
//      try {
//        Journal.listJournalIds((File) null, (Journal.JournalIdFilter) null);
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("org.apache.bookkeeper.bookie.Journal", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test09()  throws Throwable  {
//      NullStatsLogger nullStatsLogger0 = NullStatsLogger.INSTANCE;
//      AdaptiveByteBufAllocator adaptiveByteBufAllocator0 = new AdaptiveByteBufAllocator();
//      MockFile mockFile0 = new MockFile("FE`RFIuXVlk=");
//      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
//      serverConfiguration0.setMaxBackupJournals((-2595));
//      Journal journal0 = null;
//      try {
//        journal0 = new Journal((-2595), mockFile0, serverConfiguration0, (LedgerDirsManager) null, nullStatsLogger0, adaptiveByteBufAllocator0, (JournalAliveListener) null);
//        fail("Expecting exception: RuntimeException");
//
//      } catch(RuntimeException e) {
//         //
//         // 'journalMaxBackups' doesn't map to an Integer object
//         //
//         verifyException("org.apache.commons.configuration.AbstractConfiguration", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test10()  throws Throwable  {
//      NullStatsLogger nullStatsLogger0 = new NullStatsLogger();
//      CachingStatsLogger cachingStatsLogger0 = new CachingStatsLogger(nullStatsLogger0);
//      MockFile mockFile0 = new MockFile((String) null, "v,{S<0k4wI]WIjXYTp");
//      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
//      ServerConfiguration serverConfiguration1 = serverConfiguration0.setMaxJournalSizeMB((-613L));
//      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
//      Journal journal0 = null;
//      try {
//        journal0 = new Journal(1496, mockFile0, serverConfiguration1, (LedgerDirsManager) null, cachingStatsLogger0, pooledByteBufAllocator0);
//        fail("Expecting exception: RuntimeException");
//
//      } catch(RuntimeException e) {
//         //
//         // 'journalMaxSizeMB' doesn't map to a Long object
//         //
//         verifyException("org.apache.commons.configuration.AbstractConfiguration", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test11()  throws Throwable  {
//      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
//      File[] fileArray0 = new File[0];
//      LedgerDirsManager ledgerDirsManager0 = new LedgerDirsManager(serverConfiguration0, fileArray0, (DiskChecker) null);
//      CollectorRegistry collectorRegistry0 = CollectorRegistry.defaultRegistry;
//      PrometheusMetricsProvider prometheusMetricsProvider0 = new PrometheusMetricsProvider(collectorRegistry0);
//      StatsLogger statsLogger0 = prometheusMetricsProvider0.getStatsLogger("enforceMinNumRacksPerWriteQuorum");
//      AdaptiveByteBufAllocator adaptiveByteBufAllocator0 = new AdaptiveByteBufAllocator(false);
//      Journal journal0 = null;
//      try {
//        journal0 = new Journal(5, (File) null, serverConfiguration0, ledgerDirsManager0, statsLogger0, adaptiveByteBufAllocator0);
//        fail("Expecting exception: RuntimeException");
//
//      } catch(RuntimeException e) {
//         //
//         // org.evosuite.runtime.mock.java.lang.MockThrowable: java.lang.ClassNotFoundException: java.lang.String@0000000071
//         //
//         verifyException("org.apache.bookkeeper.bookie.Journal", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test12()  throws Throwable  {
//      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
//      NullStatsLogger nullStatsLogger0 = NullStatsLogger.INSTANCE;
//      MockFile mockFile0 = new MockFile("ledgerManagerFactoryDisableClassCheck", "org.apache.bookkeeper.conf.readsystemproperties");
//      PooledByteBufAllocator pooledByteBufAllocator0 = (PooledByteBufAllocator)ByteBufAllocator.DEFAULT;
//      Journal journal0 = null;
//      try {
//        journal0 = new Journal(4, mockFile0, serverConfiguration0, (LedgerDirsManager) null, nullStatsLogger0, pooledByteBufAllocator0);
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("org.apache.bookkeeper.bookie.Journal$LastLogMark", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test13()  throws Throwable  {
//      MockFile mockFile0 = new MockFile("!>>", "!>>");
//      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
//      ServerConfiguration serverConfiguration1 = serverConfiguration0.setMaxBackupJournals(5);
//      File[] fileArray0 = new File[1];
//      fileArray0[0] = (File) mockFile0;
//      LedgerDirsManager ledgerDirsManager0 = new LedgerDirsManager(serverConfiguration1, fileArray0, (DiskChecker) null);
//      Journal journal0 = null;
//      try {
//        journal0 = new Journal(4, mockFile0, serverConfiguration1, ledgerDirsManager0);
//        fail("Expecting exception: RuntimeException");
//
//      } catch(RuntimeException e) {
//         //
//         // 'journalMaxBackups' doesn't map to an Integer object
//         //
//         verifyException("org.apache.commons.configuration.AbstractConfiguration", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test14()  throws Throwable  {
//      MockFile mockFile0 = new MockFile("url");
//      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
//      serverConfiguration0.setJournalQueueSize((-748));
//      Journal journal0 = null;
//      try {
//        journal0 = new Journal((-748), mockFile0, serverConfiguration0, (LedgerDirsManager) null);
//        fail("Expecting exception: NegativeArraySizeException");
//
//      } catch(NegativeArraySizeException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("org.apache.bookkeeper.common.collections.BatchedArrayBlockingQueue", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test15()  throws Throwable  {
//      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
//      NullStatsLogger nullStatsLogger0 = new NullStatsLogger();
//      AdaptiveByteBufAllocator adaptiveByteBufAllocator0 = new AdaptiveByteBufAllocator();
//      String[] stringArray0 = new String[2];
//      stringArray0[0] = "ledgerManagerFactoryDisableClassCheck";
//      stringArray0[1] = "permittedStartupUsers";
//      serverConfiguration0.setJournalDirsName(stringArray0);
//      MockFile mockFile0 = new MockFile("limitStatsLogging");
//      Journal journal0 = null;
//      try {
//        journal0 = new Journal(4, mockFile0, serverConfiguration0, (LedgerDirsManager) null, nullStatsLogger0, adaptiveByteBufAllocator0, (JournalAliveListener) null);
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("org.apache.bookkeeper.bookie.Journal$LastLogMark", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test16()  throws Throwable  {
//      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
//      NullStatsLogger nullStatsLogger0 = NullStatsLogger.INSTANCE;
//      MockFile mockFile0 = new MockFile("enforceMinNumFaultDomainsForWrite");
//      ServerConfiguration serverConfiguration1 = serverConfiguration0.setJournalFlushWhenQueueEmpty(true);
//      File[] fileArray0 = new File[0];
//      LedgerDirsManager ledgerDirsManager0 = new LedgerDirsManager(serverConfiguration1, fileArray0, (DiskChecker) null, nullStatsLogger0);
//      Journal journal0 = null;
//      try {
//        journal0 = new Journal(1, mockFile0, serverConfiguration1, ledgerDirsManager0);
//        fail("Expecting exception: RuntimeException");
//
//      } catch(RuntimeException e) {
//         //
//         // org.evosuite.runtime.mock.java.lang.MockThrowable: java.lang.ClassNotFoundException: java.lang.String@0000000024
//         //
//         verifyException("org.apache.bookkeeper.bookie.Journal", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test17()  throws Throwable  {
//      NullStatsLogger nullStatsLogger0 = NullStatsLogger.INSTANCE;
//      AdaptiveByteBufAllocator adaptiveByteBufAllocator0 = new AdaptiveByteBufAllocator();
//      MockFile mockFile0 = new MockFile("org.apache.bookkeeper.bookie.Journal$ForceWriteRequest");
//      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
//      serverConfiguration0.setJournalMaxGroupWaitMSec((-1306));
//      Journal journal0 = null;
//      try {
//        journal0 = new Journal((-1306), mockFile0, serverConfiguration0, (LedgerDirsManager) null, nullStatsLogger0, adaptiveByteBufAllocator0, (JournalAliveListener) null);
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("org.apache.bookkeeper.bookie.Journal$LastLogMark", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test18()  throws Throwable  {
//      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
//      NullStatsLogger nullStatsLogger0 = new NullStatsLogger();
//      AdaptiveByteBufAllocator adaptiveByteBufAllocator0 = new AdaptiveByteBufAllocator();
//      serverConfiguration0.setBusyWaitEnabled(true);
//      MockFile mockFile0 = new MockFile("ignoreLocalNodeInPlacementPolicy");
//      Journal journal0 = null;
//      try {
//        journal0 = new Journal(1, mockFile0, serverConfiguration0, (LedgerDirsManager) null, nullStatsLogger0, adaptiveByteBufAllocator0, (JournalAliveListener) null);
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("org.apache.bookkeeper.bookie.Journal$LastLogMark", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test19()  throws Throwable  {
//      JournalChannel journalChannel0 = new JournalChannel((File) null, 2000000L);
//      // Undeclared exception!
//      try {
//        Journal.writePaddingBytes(journalChannel0, (ByteBuf) null, 7606);
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("org.apache.bookkeeper.bookie.Journal", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test20()  throws Throwable  {
//      JournalChannel journalChannel0 = new JournalChannel((File) null, 4);
//      UnpooledByteBufAllocator unpooledByteBufAllocator0 = UnpooledByteBufAllocator.DEFAULT;
//      EmptyByteBuf emptyByteBuf0 = new EmptyByteBuf(unpooledByteBufAllocator0);
//      Journal.writePaddingBytes(journalChannel0, emptyByteBuf0, 2);
//      assertEquals(1, emptyByteBuf0.nioBufferCount());
//  }
//
//  @Test(timeout = 4000)
//  public void test21()  throws Throwable  {
//      MockFile mockFile0 = new MockFile("FE`RFIuXVlk=");
//      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
//      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("FE`RFIuXVlk=/current/lastMark");
//      FileSystemHandling.appendStringToFile(evoSuiteFile0, "ledgerManagerFactoryDisableClassCheck");
//      File[] fileArray0 = new File[2];
//      fileArray0[0] = (File) mockFile0;
//      fileArray0[1] = (File) mockFile0;
//      LedgerDirsManager ledgerDirsManager0 = new LedgerDirsManager(serverConfiguration0, fileArray0, (DiskChecker) null);
//      Journal journal0 = null;
//      try {
//        journal0 = new Journal(5, fileArray0[0], serverConfiguration0, ledgerDirsManager0);
//        fail("Expecting exception: RuntimeException");
//
//      } catch(RuntimeException e) {
//         //
//         // org.evosuite.runtime.mock.java.lang.MockThrowable: java.lang.ClassNotFoundException: java.lang.String@0000000026
//         //
//         verifyException("org.apache.bookkeeper.bookie.Journal", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test22()  throws Throwable  {
//      MockFile mockFile0 = new MockFile("FE`RFIuXVlk=");
//      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
//      File[] fileArray0 = new File[1];
//      fileArray0[0] = (File) mockFile0;
//      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("FE`RFIuXVlk=/current/lastMark");
//      FileSystemHandling.appendStringToFile(evoSuiteFile0, "FE`RFIuXVlk=");
//      LedgerDirsManager ledgerDirsManager0 = new LedgerDirsManager(serverConfiguration0, fileArray0, (DiskChecker) null);
//      Journal journal0 = null;
//      try {
//        journal0 = new Journal(2, fileArray0[0], serverConfiguration0, ledgerDirsManager0);
//        fail("Expecting exception: RuntimeException");
//
//      } catch(RuntimeException e) {
//         //
//         // org.evosuite.runtime.mock.java.lang.MockThrowable: java.lang.ClassNotFoundException: java.lang.String@0000000025
//         //
//         verifyException("org.apache.bookkeeper.bookie.Journal", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test23()  throws Throwable  {
//      MockFile mockFile0 = new MockFile("enforceStrictZoneawarePlacement", "enforceMinNumFaultDomainsForWrite");
//      JournalChannel journalChannel0 = new JournalChannel(mockFile0, 3);
//      Journal.JournalIdFilter journal_JournalIdFilter0 = mock(Journal.JournalIdFilter.class, new ViolatedAssumptionAnswer());
//      doReturn(true).when(journal_JournalIdFilter0).accept(anyLong());
//      List<Long> list0 = Journal.listJournalIds(mockFile0, journal_JournalIdFilter0);
//      assertFalse(list0.isEmpty());
//  }
//
//  @Test(timeout = 4000)
//  public void test24()  throws Throwable  {
//      MockFile mockFile0 = new MockFile("enforceStrictZoneawarePlacement", "enforceMinNumFaultDomainsForWrite");
//      JournalChannel journalChannel0 = new JournalChannel(mockFile0, 3);
//      Journal.JournalIdFilter journal_JournalIdFilter0 = mock(Journal.JournalIdFilter.class, new ViolatedAssumptionAnswer());
//      doReturn(false).when(journal_JournalIdFilter0).accept(anyLong());
//      List<Long> list0 = Journal.listJournalIds(mockFile0, journal_JournalIdFilter0);
//      assertEquals(0, list0.size());
//  }
//
//  @Test(timeout = 4000)
//  public void test25()  throws Throwable  {
//      MockFile mockFile0 = new MockFile("FE`RFIuXVlk=");
//      JournalChannel journalChannel0 = new JournalChannel(mockFile0, 5000000L);
//      List<Long> list0 = Journal.listJournalIds(mockFile0, (Journal.JournalIdFilter) null);
//      assertTrue(list0.contains(5000000L));
//  }
//
//  @Test(timeout = 4000)
//  public void test26()  throws Throwable  {
//      MockFile mockFile0 = new MockFile("wByKN0wByKN.txn", ".");
//      MockFile.createTempFile("wByKN0wByKN.txn", "sers0~z|VC{.txn", (File) mockFile0);
//      // Undeclared exception!
//      try {
//        Journal.listJournalIds(mockFile0, (Journal.JournalIdFilter) null);
//        fail("Expecting exception: NumberFormatException");
//
//      } catch(NumberFormatException e) {
//         //
//         // For input string: \"wByKN0wByKN\"
//         //
//         verifyException("java.lang.NumberFormatException", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test27()  throws Throwable  {
//      MockFile mockFile0 = new MockFile("", "");
//      List<Long> list0 = Journal.listJournalIds(mockFile0, (Journal.JournalIdFilter) null);
//      assertTrue(list0.isEmpty());
//  }
//
//  @Test(timeout = 4000)
//  public void test28()  throws Throwable  {
//      MockFile mockFile0 = new MockFile("");
//      List<Long> list0 = Journal.listJournalIds(mockFile0, (Journal.JournalIdFilter) null);
//      assertEquals(0, list0.size());
//  }
//
//  @Test(timeout = 4000)
//  public void test29()  throws Throwable  {
//      MockFile mockFile0 = new MockFile(".txn", ".txn");
//      List<Long> list0 = Journal.listJournalIds(mockFile0, (Journal.JournalIdFilter) null);
//      assertEquals(0, list0.size());
//  }
//
//  @Test(timeout = 4000)
//  public void test30()  throws Throwable  {
//      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
//      File[] fileArray0 = new File[0];
//      LedgerDirsManager ledgerDirsManager0 = new LedgerDirsManager(serverConfiguration0, fileArray0, (DiskChecker) null);
//      NullStatsLogger nullStatsLogger0 = NullStatsLogger.INSTANCE;
//      Journal journal0 = null;
//      try {
//        journal0 = new Journal(3, (File) null, serverConfiguration0, ledgerDirsManager0, nullStatsLogger0, (ByteBufAllocator) null, (JournalAliveListener) null);
//        fail("Expecting exception: RuntimeException");
//
//      } catch(RuntimeException e) {
//         //
//         // org.evosuite.runtime.mock.java.lang.MockThrowable: java.lang.ClassNotFoundException: java.lang.String@0000000024
//         //
//         verifyException("org.apache.bookkeeper.bookie.Journal", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test31()  throws Throwable  {
//      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
//      NullStatsLogger nullStatsLogger0 = new NullStatsLogger();
//      // Undeclared exception!
//      try {
//        Journal.newJournal(5, (File) null, serverConfiguration0, (LedgerDirsManager) null, nullStatsLogger0, (ByteBufAllocator) null, (JournalAliveListener) null);
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("org.apache.bookkeeper.bookie.Journal$LastLogMark", e);
//      }
//  }
//
//  @Test(timeout = 4000)
//  public void test32()  throws Throwable  {
//      ServerConfiguration serverConfiguration0 = new ServerConfiguration();
//      Journal journal0 = null;
//      try {
//        journal0 = new Journal(2, (File) null, serverConfiguration0, (LedgerDirsManager) null);
//        fail("Expecting exception: NullPointerException");
//
//      } catch(NullPointerException e) {
//         //
//         // no message in exception (getMessage() returned null)
//         //
//         verifyException("org.apache.bookkeeper.bookie.Journal$LastLogMark", e);
//      }
//  }
//}
